# Generated by Django 2.1.7 on 2019-03-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=264, unique=True)),
                ('date', models.CharField(max_length=264)),
                ('time', models.CharField(max_length=264)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
